### ISSUE TITLE
Conflict with bitcore

### ISSUE THREAD

**Issue by dsbaars** [trapp/ethereum-bip44#1]
Wanted to try out this project but it seems to have conflict with bitcore-lib of bitcore itself.
When I just use `npm install ethereum-bip44` it says it cannot find module bitcore. When installing bitcore manually I get the following error:

```
18:38 $ node
> var bitcore = require('bitcore');
undefined
> var EthereumBip44 = require('ethereum-bip44');
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/opt/project/node_modules/ethereum-bip44/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/opt/project/node_modules/ethereum-bip44/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/project/node_modules/ethereum-bip44/es5/index.js:15:19)
```

**Comment by trapp** [comment]
Hey, thanks for the report. The examples in README.md should say `require('bitcore-lib')` instead of `require('bitcore')`. I've updated them now.

Regarding the issue that bitcore requires to have only 1 instance I'd suggest that you use npm with a version greater than 3.0.0. This will result in a flat node_module hierarchy with bitcore-lib available at the top level.

Otherwise you will have to install bitcore-lib on the top level and install this library afterwards or remove the bitcore-lib folder inside ethereum-bip44 manually.
